carts/urls.py
from django.urls import path, include

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view
        )



urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('checkout/success/', checkout_done_view, name='success'),
]
app_name = 'carts'

products/urls.py
from django.urls import path, include

from .views import (
        ProductListView, 
        #product_list_view, 
        #ProductDetailView, 
        #product_detail_view,
        #ProductFeaturedListView,
        #ProductFeaturedDetailView,
        ProductDetailSlugView
        )



urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug>/', ProductDetailSlugView.as_view(), name='detail'),
]
app_name = 'products'

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% include 'base/css.html' %}
    <title>E-commerce Website</title>
  </head>
  <body class="container-lg">
    {% include 'navbar.html' %}
    <div class='container'>
        {% block body %}
        {% endblock %}
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
    </div>
    {% include 'base/js.html' %}
    <canvas id="canvas"></canvas>

        
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% url 'home' as home_url %}
{% url 'products:list' as product_list_url %}
{% url 'contact' as contact_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'login' as login_url %}
{% url 'carts:home' as cart_url %}
{% load static %}

{% block body %}
    
<div class="jumbotron">
  <h1 class="display-4">Welcome to GreenCommerceToday.com</h1>
  <h3>{{ title }}</h3>
  <p class="lead">A new green experience for eCommerce. <br> We are making the world the same place</p>
  <hr class="my-4">
  <p>Why don't you check us out and see how amazing it is!</p>
  <a class="btn btn-primary btn-lg" href="{{ product_list_url }}">See what's new</a>
</div>
    {% comment %} <img src='{% static "img/AMAZON.png" %}' class='img-fluid'/> {% endcomment %}



{% endblock %}

templates/navbar.html
{% url 'home' as home_url %}
{% url 'products:list' as product_list_url %}
{% url 'contact' as contact_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'login' as login_url %}
{% url 'carts:home' as cart_url %}
{% url 'analytics' as analytics_url %}
{% load static %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class='container'>
    <a class="navbar-brand" href="{{ home_url }}">
        <img src='{% static "img/lion.png" %}'  class='d-inline-block align-top' width='30' height='30' />
        eCommerce
    </a>
   

   
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav">
                <li class="nav-item {% if request.path == home_url %} active {% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home</a>
                    </li>
                    <li class="nav-item {% if request.path == product_list_url %} active {% endif %}">
                        <a class="nav-link" href="{{ product_list_url }}">Product</a>
                    </li>
                    <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="#">Action</a>
                          <a class="dropdown-item" href="#">Another action</a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                      </li> -->
                      <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
                        <a class="nav-link" href="{{ contact_url }}">Contact</a>
                    </li>
                    <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
                        <a class="nav-link" href="{{ analytics_url }}">Analytics</a>
                    </li>
            </ul>

            {% include 'search/snippets/search-form.html' %}

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item ml-auto">
                        <a class="nav-link" href="{% url 'logout'%}">Log Out</a>
                    </li>
                {% else %}
                <li class="nav-item navbar-right {% if request.path == register_url %} active {% endif %}">
                    <a class="nav-link" href="{{ register_url }}">Sign Up</a>
                </li>
                <li class="nav-item navbar-right {% if request.path == login_url %} active {% endif %}">
                <a class="nav-link" href="{{ login_url }}">Sign In</a>
                </li>
                {% endif %}
                <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
                    <a class="nav-link" href="{{ cart_url }}">(<span class='navbar-cart-count'> {{ request.session.cart_items }}</span>)<i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
                </li>
            </ul>
           
       
        
    </div>
    </div>
</nav>

<!--
<div class='row mb-3'>
    <div class ='col-12 col-sm-10 col-md-6 col-lg-4 ml-auto'>
        <input type='text' class='form-control' placeholder=Search>  
    </div>
</div>
-->